### PR TITLE
build linux/mac with openmp

### PR DESCRIPTION
**Pull request by minrk**
not Windows (#61), only because I don't know how to do that. It's unclear if Windows should use intel-openmp or llvm-openmp, and whether we can just use [FindOpenMP](https://cmake.org/cmake/help/latest/module/FindOpenMP.html) in cmake and it will Just Work.

### CODE REVIEW

**Comment by traversaro** [comment]
I am probably just missing something about the mumps structure and build system, but does it make sense to enable `openmp` also for `mumps_seq` or it should be enabled just for `mumps_par`?

**Comment by minrk** [comment]
par == multiprocess with mpi, seq == single process. openmp threads are within each process, so are appropriate in both (omp threads are slightly _less_ likely to be used with mpi, where each process is often allocated only one thread).

**Comment by traversaro** [comment]
> par == multiprocess with mpi, seq == single process. openmp threads are within each process, so are appropriate in both (omp threads are slightly _less_ likely to be used with mpi, where each process is often allocated only one thread).

Thanks, that is much more clear now!

**Comment by minrk** [comment]
I've done some reading, and openmp on windows appears to be a hornet's nest, so I think we should wait to tackle that:

- https://github.com/conda-forge/conda-forge.github.io/issues/1269
- https://github.com/conda-forge/conda-forge.github.io/issues/1597

It _seems_ like this might start to get better soon with the imminent flang update in #119:

- https://github.com/conda-forge/openblas-feedstock/pull/115

**Pull request merged**
