### PR TITLE
5.6.2

### LINKED ISSUE #64: Windows package installs .lib files in Library\bin\
On Windows, the `mumps-seq`  package installs the files:
* `cmumps.lib`
* `dmumps.lib`
* `smumps.lib`
* `zmumps.lib`

in the `Library\bin\` directory, instead of the `Library\lib` directory in which .lib files are usually installed. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
(ipopt-tests) C:\src\ipopt-tests\Ipopt\build-nmake>conda list
# packages in environment at C:\Users\STraversaro\Miniconda3\envs\ipopt-tests:
#
# Name                    Version                   Build  Channel
c-compiler                1.1.1                he774522_1    conda-forge
clangdev                  5.0.0                   flang_3  [flang]  conda-forge
cmake                     3.18.3               h39d44d4_0    conda-forge
compilers                 1.1.1                         1    conda-forge
cxx-compiler              1.1.1                h74a9793_1    conda-forge
flang                     5.0.0           he025d50_20180525    conda-forge
flang_win-64              5.0.0                  20180525    conda-forge
fortran-compiler          1.1.1                he67e8c7_1    conda-forge
gettext                   0.19.8.1          hfbb10ce_1004    conda-forge
intel-openmp              2020.2                      254
lapack                    3.9.0                    netlib    conda-forge
libblas                   3.9.0           2_h8933c1f_netlib    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libglib                   2.66.2               h35efcdc_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0           2_h8933c1f_netlib    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mkl                       2020.2                      256
msys2-conda-epoch         20160418                      1
mumps-seq                 5.2.1                h0f4c095_9    conda-forge
ninja                     1.10.1               h587dcfd_2    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pkg-config                0.29.2            h4a39e8b_1008    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
vs2017_win-64             19.16.27038          h2e3bad8_2    conda-forge
vswhere                   2.7.1                h21ff451_0
zlib                      1.2.11            h62dcd97_1010    conda-forge

(ipopt-tests) C:\src\ipopt-tests\Ipopt\build-nmake>
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(ipopt-tests) C:\src\ipopt-tests\Ipopt\build-nmake>conda info

     active environment : ipopt-tests
    active env location : C:\Users\STraversaro\Miniconda3\envs\ipopt-tests
            shell level : 2
       user config file : C:\Users\STraversaro\.condarc
 populated config files : C:\Users\STraversaro\.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\STraversaro\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\STraversaro\Miniconda3\pkgs
                          C:\Users\STraversaro\.conda\pkgs
                          C:\Users\STraversaro\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\STraversaro\Miniconda3\envs
                          C:\Users\STraversaro\.conda\envs
                          C:\Users\STraversaro\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


(ipopt-tests) C:\src\ipopt-tests\Ipopt\build-nmake>
```
</details>

### LINKED ISSUE #83: Support for newer versions?
### Comment:

Mumps is currently at version 5.5.1, but version 5.2.1 is the latest version available from conda-forge.  Would it be possible to update to a more recent version?

### PR DESCRIPTION
**Pull request by minrk**
closes #64
closes #83 
closes #98 

no longer need our shared-library patches

haven't looked at Windows yet

### CODE REVIEW

**Comment by traversaro** [comment]
Windows fails with:
~~~
2023-12-12T09:37:47.7893090Z -- Looking for Fortran cheev
2023-12-12T09:37:48.3337810Z -- Looking for Fortran cheev - found
2023-12-12T09:37:48.3352346Z -- Found LAPACK: D:/bld/mumps_1702373512541/_h_env/Library/lib/lapack.lib;D:/bld/mumps_1702373512541/_h_env/Library/lib/blas.lib  
2023-12-12T09:37:48.3428600Z -- Configuring done (26.5s)
2023-12-12T09:37:48.3521571Z CMake Error at CMakeLists.txt:128 (add_library):
2023-12-12T09:37:48.3522693Z   Cannot find source file:
2023-12-12T09:37:48.3523316Z 
2023-12-12T09:37:48.3524027Z     src/mumps_size.c
2023-12-12T09:37:48.3524583Z 
2023-12-12T09:37:48.3525152Z   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
2023-12-12T09:37:48.3525894Z   .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
2023-12-12T09:37:48.3526562Z   .f95 .f03 .hip .ispc
2023-12-12T09:37:48.3527119Z 
2023-12-12T09:37:48.3527544Z 
2023-12-12T09:37:48.4032312Z CMake Error at CMakeLists.txt:128 (add_library):
2023-12-12T09:37:48.4034075Z   No SOURCES given to target: mumps_common
2023-12-12T09:37:48.4034775Z 
~~~

Based on https://github.com/scivision/mumps/blob/44fb7e74b5780a3ea1c26a76a55298a2c34279fe/cmake/mumps.cmake#L62, I guess we just need to remove that file from the CMakeLists.txt (and add some other files that I have been added). @minrk  I can directly modify the CMakeLists.txt in your branch if that is ok for you.

**Comment by minrk** [comment]
@traverso thanks for the offer! I've updated the CMakeLists based on a diff of `src/Makefile` from 5.2.1 to 5.6.2, hopefully that will be enough.

**Comment by minrk** [comment]
Everything appears to work except mac arm builds, which can't find libgfortran at link time for mysterious reasons:

```
/Users/runner/miniforge3/conda-bld/mumps_1702375244650/_build_env/bin/arm64-apple-darwin20.0.0-gfortran -fPIC -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/mumps_1702375244650/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mumps_1702375244650/work=/usr/local/src/conda/mumps-seq-5.6.2 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mumps_1702375244650/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla=/usr/local/src/conda-prefix -fallow-argument-mismatch -fPIC -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/mumps_1702375244650/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mumps_1702375244650/work=/usr/local/src/conda/mumps-seq-5.6.2 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mumps_1702375244650/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla=/usr/local/src/conda-prefix -fallow-argument-mismatch -fPIC -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/mumps_1702375244650/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mumps_1702375244650/work=/usr/local/src/conda/mumps-seq-5.6.2 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/mumps_1702375244650/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla=/usr/local/src/conda-prefix -fallow-argument-mismatch -shared mpi.o mpic.o elapse.o -o libmpiseq_seq.dylib
ld: library not found for -lgfortran
collect2: error: ld returned 1 exit status
```

I copied https://github.com/conda-forge/climlab-feedstock/pull/62 which faced the same error, we'll see if the same fix works.

@traverso can you check if the Windows paths are correct now? I took a stab at #64 and the updated expectations in meta.yaml pass, but I'm not 100% sure I've updated the expectations correctly (DLLs in bin, LIBs in lib).

**Comment by traversaro** [comment]
> @Traverso thanks for the offer! I've updated the CMakeLists based on a diff of `src/Makefile` from 5.2.1 to 5.6.2, hopefully that will be enough. I'll ping you if it turns out to be any more complicated than that.

Great, thanks!

**Comment by traversaro** [comment]
> @Traverso can you check if the Windows paths are correct now? I took a stab at #64 and the updated expectations in meta.yaml pass, but I'm not 100% sure I've updated the expectations correctly (DLLs in bin, LIBs in lib).

Everything seems correct now. Just FYI, since CMake 3.14 the default arguments for `DESTINATION` already do the right thing, so a possible fix is also to just get rid of `DESTINATION` argument of `install(TARGETS ...)` at all.

**Comment by minrk** [comment]
I'm at a loss on the mac-arm64-nompi builds, which are the only ones failing now. I don't know what else to try. I assume I'm just missing something in the FFLAGS or the right package in build and/or host.

**Review by traversaro — APPROVED** [review]

**Comment by minrk** [comment]
actually, I do have an idea for possibly missing linker flags on the failing entry

**Comment by minrk** [comment]
Huzzah! 5769967ad271e2b84c1c286e0911e4adf770b501 works. The problem was $LDFLAGS wasn't getting passed along to libpord_seq and libmpi_seq, and adding them fixes things. One more commit to make sure that the addition of `libgfortran` to host dependencies wasn't necessary, and it should be all set.

**Pull request merged**
