### PR TITLE
WIP: Windows support

### PR DESCRIPTION
**Pull request by richardotis**
This will definitely not work until scotch adds Windows support: https://github.com/conda-forge/scotch-feedstock/pull/8

### CODE REVIEW

**Comment by basnijholt** [comment]
@richardotis it is great that you are willing to work on this! 

I could certainly use the Windows build to build [kwant](https://github.com/conda-forge/kwant-feedstock) for Windows.

But like I mentioned in https://github.com/conda-forge/scotch-feedstock/pull/8, that PR is not ready yet and I am afraid I don't know how to fix it from here (not a Windows guy...)

So in order to build MUMPS for Windows, I suggest starting with SCOTCH :)

**Comment by richardotis** [comment]
New PR for scotch Windows support: https://github.com/conda-forge/scotch-feedstock/pull/13

**Comment by richardotis** [comment]
I've been able to use m2w64-toolchain, m2w64-openblas and CMake to build MUMPS 5.0.2 on Windows: https://gist.github.com/richardotis/a34d7b1d483d246505913e44813eb248

I haven't put a conda build together yet, but I wanted to document what I've done so far.

```
# put CMakeLists.txt in mumps source root
mkdir build
cd build
cmake .. -G "MinGW Makefiles"
mingw32-make
# to test build:
aexample.exe < ..\examples\input_simpletest_real
```

**Comment by richardotis** [comment]
WIP meta.yaml (will not work on conda-forge yet, requires msys2 channel):
I've hardcoded the mumps source path because I manually drop the above CMakeLists.txt file into the source directory; I am having trouble getting the patch machinery to work.
```
{% set name = "mumps" %}
{% set version = "5.0.2" %}
{% set sha256 = "77292b204942640256097a3da482c2abcd1e0d5a74ecd1d4bab0f5ef6e60fe45" %}
{% set variant = "openblas" %}

package:
  name: mumps
  version: {{ version }}

source:
#  fn: MUMPS_{{ version }}.tar.gz
  path: C:\\Users\rotis\git\MUMPS_5.0.2
#  sha256: {{ sha256 }}
  patches:
    - mumps_mpi.patch
build:
  number: 203
  features:
    - blas_{{ variant }} # [not win]

requirements:
  build:
    - toolchain # [not win]
    - blas 1.1 {{ variant }} # [not win]
    - openblas 0.2.19|0.2.19.* # [not win]
    - gcc # [not win]
    - m2w64-toolchain # [win]
    - m2w64-openblas # [win]
    - cmake # [win]
    - patch # [win]
  run:
    - blas 1.1 {{ variant }} # [not win]
    - openblas 0.2.19|0.2.19.* # [not win]
    - libgfortran # [not win]
    - m2w64-openblas # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libdmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libmumps_common.a"  # [not win]
    - test -f "${PREFIX}/lib/libpord.a"  # [not win]
    - test -f "${PREFIX}/include/dmumps_struc.h"  # [not win]
    - if not exist "%LIBRARY_LIB%\\libdmumps.a" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libmumps_common.a" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libpord.a" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\dmumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\mumps_mpi.h" exit 1  # [win]


about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (â€œMUltifrontal Massively Parallel Solverâ€) is a package for solving 
    systems of linear equations of the form Ax = b, where A is a square sparse 
    matrix that can be either unsymmetric, symmetric positive definite, or 
    general symmetric, on distributed memory computers. MUMPS implements a 
    direct method based on a multifrontal approach which performs a Gaussian 
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - basnijholt
```

**Comment by basnijholt** [comment]
@richardotis there is OpenBLAS for Windows now on conda-forge.

**Comment by richardotis** [comment]
@basnijholt Can you link to the relevant discussion?

**Comment by basnijholt** [comment]
There is no discussion I was referring to, just https://github.com/conda-forge/openblas-feedstock and https://github.com/conda-forge/toolchain-feedstock both have Windows builds now.

**Comment by richardotis** [comment]
Key stuff looks like it's here: https://github.com/conda-forge/openblas-feedstock/pull/34
And an example recipe here: https://github.com/conda-forge/openblas-feedstock/blob/40320b71be5be2f13026cb8541f49dfde7825c96/recipe/meta.yaml

conda-forge is shipping a working flang on Windows now, so in principle all of our scientific software compilation woes are solved. I'll look into this.

**Comment by richardotis** [comment]
Superseded by #25

**Pull request closed without merging**
