### PR TITLE
MSVC/Flang support (Windows)

### PR DESCRIPTION
**Pull request by richardotis**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR switches the Windows build over to the newer compiler infrastructure using MSVC and Flang, retiring the MinGW build. According to a reverse dependency analysis, the only feedstock which will be affected is ipopt (and I have ongoing work to address that in https://github.com/conda-forge/ipopt-feedstock/pull/34).

### CODE REVIEW

**Comment by richardotis** [comment]
It looks like the way OpenBLAS handles this is forcing the use of clang: https://github.com/conda-forge/openblas-feedstock/blob/631acd1244709ed8872494b1d40d0195b4049e4f/recipe/bld.bat

Possibly related to https://github.com/flang-compiler/flang-driver/pull/75

I'll test this, but I think it's fine to use Clang here to build shared libraries while downstream uses MSVC. Local testing appears promising.

**Comment by richardotis** [comment]
This is ready for review.

**Comment by isuruf** [comment]
> I'll note that I have to use WINDOWS_EXPORT_ALL_SYMBOLS to get the Fortran examples to link, and this appears to crash MSVC, but not clang-cl.

It's not MSVC that crashes, it's CMake that crashes. See https://github.com/conda-forge/pymdi-feedstock/blob/c620ef2d8069301a194aef0fe41658ac4568fcd8/recipe/bld.bat#L8-L11

**Comment by richardotis** [comment]
Any comments from the feedstock maintainers?

**Comment by richardotis** [comment]
I'd be interested in those using downstream packages to try this packaging of mumps. I packaged this on the pycalphad anaconda.org channel, and while it mostly works, there seems to be a few downstream test failures. The mumps tests themselves seem to pass without a problem, so I'm not sure if it's a downstream issue. (This was never an issue with the MinGW-based builds.)

For me the dependency chain looks like
`mumps (tests pass) -> ipopt (6/44 tests fail) -> pycalphad (6/123 tests fail)`

I'm still investigating, but I wanted to give a heads up to other maintainers in case they want to test against their own packages.

**Comment by minrk** [comment]
I don't have any relevant knowledge of windows builds, so I'd just have to trust you, but it looks AOK to me. I'd like to let @jbweston weight in, but I'm also okay merging this if we don't get any negative feedback soon.

**Comment by moorepants** [comment]
Shall this be merged?

**Comment by richardotis** [comment]
By the way, I investigated the downstream test failures and confirmed the exact same ipopt test failures when using the (current) MinGW-based conda-forge mumps.

I still don't know what's causing the downstream failures, but I believe this is safe to merge.

**Comment by moorepants** [comment]
@conda-forge/mumps Can an owner of this repo approve and merge this PR? Seems like there aren't any objections.

**Comment by basnijholt** [comment]
I know too little about Windows builds to make a good judgement.

However, if no one has objections I will merge tomorrow ;)

**Comment by moorepants** [comment]
Thanks!

**Comment by moorepants** [comment]
It looks like the build on master failed.

**Comment by richardotis** [comment]
@conda-forge-admin please rerender

**Pull request merged**
