### PR TITLE
parallel build

### LINKED ISSUE #14: build with MPI
People need MUMPS built with MPI for use in PETSc, and I'm trying to figure out the best way to go about it. Would it be possible for this recipe to be built with MPI? Or should that be done as a separate `mumps-mpi` package? Is there a downside to having built with MPI when running in serial?

If it should be a separate package that can be done on this repo in a branch (as is done with scotch/pt-scotch), or a new feedstock. Preferences?

cf https://github.com/conda-forge/petsc-feedstock/issues/12

### PR DESCRIPTION
**Pull request by minrk**
build with mpich, ptscotch, scalapack

- removes mpi patch
- consolidates common Makefile.inc

closes #14

This makes the `mumps` package itself an mpi-linked version. If there's a reason to keep serial and mpi builds separate, this can be handled as a separate branch and/or feature (pending http://github.com/conda-forge/staged-recipes/pull/1501).

### CODE REVIEW

**Comment by basnijholt** [comment]
As I just commented in #14, I think this can be merged.

Maybe do a rerender first since it has been a while?

**Comment by basnijholt** [comment]
I guess you can also add yourself as a `recipe-maintainer` :)

**Comment by minrk** [comment]
re-rendered and added myself

**Comment by basnijholt** [comment]
Thanks! Will merge whenever the CIs finish 👍

**Pull request merged**
