### PR TITLE
5.1.2

### PR DESCRIPTION
**Pull request by minrk**
mumps_mpi.patch doesn't seem to be necessary anymore

### CODE REVIEW

**Comment by minrk** [comment]
happy to wait for #30 before applying this one, in case the other patch needs updating

**Comment by jbweston** [comment]
> happy to wait for #30 before applying this one, in case the other patch needs updating

Seems it will indeed need changing. AFAICT from the appveyor logs the source files are not in the same place in 5.1.2 as in 5.0.2

**Comment by minrk** [comment]
Rebased now that #30 has landed. It might work, since it's no longer a patch that needs to be applied, which could make it easier to maintain in the future.

**Comment by jbweston** [comment]
Seems that the Makefile for 5.0.2 and 5.1.2 is quite different. This will require taking a closer look to see exactly what the differences are.

**Pull request merged**
