### PR TITLE
Windows support via msys2

### PR DESCRIPTION
**Pull request by richardotis**

### CODE REVIEW

**Comment by richardotis** [comment]
@conda-forge-admin, please rerender

**Comment by richardotis** [comment]
@basnijholt I think this is ready for your review

**Comment by richardotis** [comment]
@minrk Could you take a look at this?

**Comment by basnijholt** [comment]
Thanks for the amazing work!

> @basnijholt I think this is ready for your review

Sorry missed this. To be honest I am not really that familiar with building for Windows.

Maybe we can ask @isuruf to have a look?

**Comment by richardotis** [comment]
It would be good to review this soon so we can merge https://github.com/conda-forge/ipopt-feedstock/pull/18, which might fix some issues users have been having ( https://github.com/conda-forge/ipopt-feedstock/issues/19 )

**Comment by basnijholt** [comment]
I am going ahead and merged this, I've asked for help with reviewing on Gitter several times, but no response.

I am sorry that it took so incredibly long! Thanks a lot for your contribution 😄

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
I will merge as soon as the tests succeed.

**Comment by basnijholt** [comment]
@richardotis, after re-rendering some test seems to fail: https://ci.appveyor.com/project/conda-forge/mumps-feedstock/build/1.0.10

**Comment by richardotis** [comment]
@basnijholt Looks like a hiccup on the CI. I restarted the job and now it seems to pass.

**Comment by richardotis** [comment]
I want to note for the record that if someone finds this PR and is having an issue getting something besides double floating point arithmetic to work in MUMPS on Windows, here we are only building support for **d**oubles in MUMPS on Windows (lib**d**mumps.dll).

**Comment by jbweston** [comment]
> here we are only building support for doubles in MUMPS on Windows (libdmumps.dll).

Once #28 is merged we will have support for all datatypes.

**Pull request merged**
