### PR TITLE
Add missing int_def header file on Windows

### PR DESCRIPTION
**Pull request by akhmerov**
This is a follow-up of #100, which was closed too hastily.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
So far I only check that the file is present (it isn't present yet).

**Comment by minrk** [comment]
Thanks for the test! I think it should work now, will wait for CI to confirm.

**Comment by akhmerov** [comment]
:+1: sorry for the simultaneous push BTW

**Comment by minrk** [comment]
I should apologize! It's your PR. Nice that git makes it easy to fix my mistake.

**Pull request merged**
