### PR TITLE
5.1.2

### PR DESCRIPTION
**Pull request by jbweston**
This is just for me to experiment with building for windows before pushing to the fork of @minrk.

### CODE REVIEW

**Comment by minrk** [comment]
I'm totally happy to let you finish it in this PR. I can close mine in favor of this one.

**Comment by minrk** [comment]
I added a couple of changes that might get this working:

- do not install libseq mpi headers (these should be private build-time things, not used by other packages)
- add missing mumps_common.c source
- fix case on c source file extensions (shouldn't be relevant, but might come up if Windows builds ever happen on case-sensitive filesystem)

**Comment by basnijholt** [comment]
Great work! LGTM.

**Comment by minrk** [comment]
Thanks @jbweston!

**Pull request merged**
