### PR TITLE
build MUMPS for all datatypes on Windows

### PR DESCRIPTION
**Pull request by jbweston**
Previously only real double precision was built.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`

### CODE REVIEW

**Comment by jbweston** [comment]
I don't want to bump the build number in case #27 is merged before this.

Is there really no way to have the version bumped automatically when this is merged into master?

**Comment by jbweston** [comment]
@conda-forge-admin please re-render

**Comment by jbweston** [comment]
specifically, we needed [this pull request](https://github.com/conda-forge/python-libarchive-c-feedstock/pull/7) to be merged, and everything to propagate through

**Comment by jbweston** [comment]
@conda-forge-admin please re-render

**Comment by jbweston** [comment]
@conda-forge-admin please re-render

**Comment by basnijholt** [comment]
Great work, thanks a lot!

**Pull request merged**
