### PR TITLE
Bump build number, update URL and add patch to build with METIS 5.1.1

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
> Based on [coin-or/coinbrew#47 (comment)](https://github.com/coin-or/coinbrew/issues/47#issuecomment-664834657) probably we should pass `-fallow-argument-mismatch` somewhere.

See also https://github.com/conda-forge/scalapack-feedstock/pull/30#issuecomment-1061196317 .

**Comment by traversaro** [comment]
> Some macos builds fail with:
> 
> ```
> Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to LOGICAL(4)
> mpi.f:575:72:
> 
>   575 |          CALL MUMPS_COPY_LOGICAL( SENDBUF, RECVBUF, CNT )
>       |                                                                        1
> Error: Type mismatch in argument ‘r’ at (1); passed INTEGER(4) to LOGICAL(4)
> mpi.f:577:72:
> 
>   577 |          CALL MUMPS_COPY_REAL( SENDBUF, RECVBUF, CNT )
>       |                                                                        1
> Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to REAL(4)
> mpi.f:577:72:
> 
>   577 |          CALL MUMPS_COPY_REAL( SENDBUF, RECVBUF, CNT )
>       |                                                                        1
> Error: Type mismatch in argument ‘r’ at (1); passed INTEGER(4) to REAL(4)
> mpi.f:580:72:
> 
>   580 |          CALL MUMPS_COPY_DOUBLE_PRECISION( SENDBUF, RECVBUF, CNT )
>       |                                                                        1
> Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to REAL(8)
> mpi.f:580:72:
> 
>   580 |          CALL MUMPS_COPY_DOUBLE_PRECISION( SENDBUF, RECVBUF, CNT )
>       |                                                                        1
> Error: Type mismatch in argument ‘r’ at (1); passed INTEGER(4) to REAL(8)
> mpi.f:582:72:
> ```
> 
> Based on [coin-or/coinbrew#47 (comment)](https://github.com/coin-or/coinbrew/issues/47#issuecomment-664834657) probably we should pass `-fallow-argument-mismatch` somewhere.

The osx-64 fortran compiler is gfortran 12, while in the latest build was gfortran 9, that is the reason why we now need the workaround also for osx-64 .

**Review by minrk — APPROVED** [review]
Title says draft, but it's all looking okay to me, now. LMK when you think this is ready.

**Comment by traversaro** [comment]
> Title says draft, but it's all looking okay to me, now. LMK when you think this is ready.

It is not, basically mumps hardcode some indeces that changed between metis 5.1.0 and 5.1.1 and so at runtime in some cases it would crash, see https://github.com/KarypisLab/METIS/issues/71#issuecomment-1696082046 . I wanted to see if there was something in mumps recipe itself that could capture this, but unfortunatly that is not the case.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
If anyone has any idea of a test we could add here to fail as `python -c "import kwant; kwant.test()"` fails, it would be great.

**Comment by traversaro** [comment]
At the moment the build is failing as on linux-ppc64le there is not metis 5.1.1 build, see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4857#issuecomment-1699470569 for the full context.

**Comment by traversaro** [comment]
> At the moment the build is failing as on linux-ppc64le there is not metis 5.1.1 build, see [conda-forge/conda-forge-pinning-feedstock#4857 (comment)](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4857#issuecomment-1699470569) for the full context.

This was fixed by https://github.com/conda-forge/metis-feedstock/pull/40 , the PR should now be ready.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The PR is ready for review @conda-forge/mumps

**Comment by traversaro** [comment]
> The PR is ready for review @conda-forge/mumps

It would be great to merge this, so we can unblock https://github.com/conda-forge/mumps-feedstock/pull/89, thanks!

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
