### PR TITLE
Rebuild for gfortran 7 for OSX (fixed)

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #48

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by minrk** [comment]
I think `patch` is running afoul of strict channel priority. The conda-forge patch package has no builds for Windows, despite the package description suggesting it's a windows-only package.

From [this issue](https://github.com/conda-forge/patch-feedstock/issues/1), it looks like we want `m2-patch`, which is only on the [msys2 channel](https://anaconda.org/msys2/m2-patch). I assume that's not on the default channel list? If it is, that's the package we want.

**Comment by beckermr** [comment]
Ok. I’ll give it a go in a bit.

**Comment by beckermr** [comment]
@minrk do you understand this?

```
Package libgfortran conflicts for:
parmetis -> mpich[version='>=3.2,<3.3.0a0'] -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
liblapack==3.8.0[build=*netlib] -> libgfortran[version='>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
ptscotch -> mpich[version='>=3.2,<3.3.0a0'] -> libgfortran[version='>=4.0.0,<5.0.0.a0']
liblapack==3.8.0[build=*netlib] -> libblas=3.8.0 -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libgcc -> libgfortran==3.0.1
scotch -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0']
scalapack -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
libblas==3.8[build=*netlib] -> libgfortran[version='>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
ptscotch -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0']
openmpi -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']
scalapack -> openblas[version='>=0.2.20,<0.2.21.0a0'] -> libgcc -> libgfortran==3.0.1
libgfortran[version='>=4.0.0,<5.0.0.a0']
Package libgfortran-ng conflicts for:
scalapack -> openblas[version='>=0.2.20,<0.2.21.0a0'] -> libgfortran-ng[version='>=3.0']
liblapack==3.8.0[build=*netlib] -> libblas=3.8.0 -> openblas[version='>=0.3.6,<0.3.7.0a0'] -> libgfortran-ng[version='>=3.0']
```

This line, in particular, is weird to me

```
scotch -> libgfortran[version='>=3.0,<4.0.0.a0|>=3.0.1,<4.0.0.a0']
```

The scotch package has no fortran dependence.

**Comment by beckermr** [comment]
I'm trying a rebuild of scotch here: https://github.com/conda-forge/scotch-feedstock/pull/42

**Comment by beckermr** [comment]
I'm closing this issue and moving on. I don't have the bandwidth right now to rebuild this one.

**Pull request closed without merging**
