### PR TITLE
update the domain name

### PR DESCRIPTION
**Pull request by akhmerov**
Mumps migrated to a new domain, which broke the builds.

### CODE REVIEW

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by davidbrochart** [comment]
It looks like you need to ask for a [download request](https://mumps-solver.org/index.php?page=dwnld#form)?

**Comment by akhmerov** [comment]
No, the link isn't advertised on the website, but it's working, and has been working for a while. Right now the download succeeds, but the patches fail.

**Comment by davidbrochart** [comment]
Ah yes I just saw it, thanks.

**Comment by traversaro** [comment]
Superseded by https://github.com/conda-forge/mumps-feedstock/pull/88 .

**Pull request closed without merging**
